fix subtle testing concurrency bug (#1134)
Due to the increment happening first, once in a blue moon, we'd end up with a failing test
```
Error:  Failures: 
Error:    ExceptionHandlingTest.lambda$shouldShortcircuitOnException$1:48 
Expecting actual:
  100L
to be less than:
  100L 
```